version: "3.8"

services:
  app:
    container_name: document-frontend
    image: document-frontend-image
    build: 
      context: .
    
    stdin_open: true
    tty: true
    volumes:
      - /app
    network_mode: "host"
